amf_1:
  url: /namf-evts/v1
  ip: 192.168.79.132
  port: 8080
sbi:
  ip: 192.168.79.129
  port: 1112
smf_1:
  url: /nsmf_event-exposure/v1
  ip: 192.168.79.133
  port: 8080
nwdaf-sbi:
  name: oai-nwdaf-nbi-gateway
  url: /nnwdaf-eventssubscription/v1
